### ISSUE TITLE
local variable 'body' referenced before assignment

### ISSUE THREAD

**Issue by AlbertWigmore** [jxwolstenholme/btsmarthub_devicelist#3]
Hi,

I am currently using HomeAssistant 0.84.3 and run into an issue with trying to use the BT SmartHub component which uses this library in order to retrieve a list of active devices.

Returns the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 176, in async_setup_platform
    platform.get_scanner, hass, {DOMAIN: p_config})
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bt_smarthub.py", line 29, in get_scanner
    scanner = BTSmartHubScanner(config[DOMAIN])
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bt_smarthub.py", line 45, in __init__
    data = self.get_bt_smarthub_data()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bt_smarthub.py", line 84, in get_bt_smarthub_data
    router_ip=self.host, only_active_devices=True)
  File "/usr/local/lib/python3.6/site-packages/btsmarthub_devicelist/btsmarthub_devicelist.py", line 93, in get_devicelist
    serverNonce = body['reply']['actions'][0]['callbacks'][0]['parameters']['nonce']
UnboundLocalError: local variable 'body' referenced before assignment
```

I then tried to check if it was an issue with HomeAssistant and so called the following function locally to test (Python 3.5.2).

`bt.get_devicelist(router_ip='192.168.1.254', only_active_devices=True)`

Which resulted in the same error.

Any help would be appreciated in getting this to work.

**Comment by d0ugal** [comment]
It looks like `body` is never defined if the response doesn't have a 200 status code. https://github.com/jxwolstenholme/btsmarthub_devicelist/blob/master/bt_smarthub_devicelist/btsmarthub_devicelist.py#L86-L89

Can you find the "Invalid response from Smart Hub:" error log from HA? If so, what comes after that mgiht give a clue.

Otherwise you could setup logging before you locally to test with something like https://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log-file.

**Comment by AlbertWigmore** [comment]
On HA it comes back with a 404 response:

`2019-01-06 19:12:19 ERROR (SyncWorker_11) [btsmarthub_devicelist.btsmarthub_devicelist] Invalid response from Smart Hub: <Response [404]>`

**Comment by jxwolstenholme** [comment]
Hi Albert,

Thanks for bringing this up. Not entirely sure why it would be throwing a 404 error but I will look in to it.

Just out of curiosity, are you sure that you have a Smart Hub and not a different BT router? If yes, I'd be interested to see how close your serial number is to mine and if they've done something different as I am yet to receive a 404 from a call to my router.

Evidently there needs to be a better way to handle these errors.

**Comment by AlbertWigmore** [comment]
I have a BT Smart Hub - Type B
Firmware Version: v0.09.06.05093-BT

Hope that helps, happy to test anything on this end to get it working.

**Comment by d0ugal** [comment]
Just to add another data point, since it all works fine for me. These are my details, taken from: http://192.168.1.254/0000016400/gui/#/technicalLog/information

Product name: `BT Hub 6A`
Firmware version: `SG4B1000B540`
Firmware updated: `13-Oct-2018`
Board version: `1.0`
Gui version: `1.64.0`

I couldn't find anything related to a 'type' and our versions seem to be totally different. So it seems we have different devices?

**Comment by jxwolstenholme** [comment]
Ahhh, okay.

I've also got a BT Hub 6A 

- I did some googling and found that there is both a 6A and a 6B, I think potentially something to do with differentiating between FTTP and FTTC BT connections.

Unfortunately, without having the device that @AlbertWigmore has I'm not sure that there is anything I can realistically do to solve the problem as they are made by different manufacturers. 

If, however, you can work it out with your router by all means submit a PR and I will update the package.

In the meantime, I will update the HA device tracker page to explain the issue.

Sorry to be so useless!

**Comment by colesadam** [comment]
@jxwolstenholme I might be able to look at this - I can see on my router that I get a 404 back from any post to /cgi/json-req but I'm wondering how you found out the required post and body for the previous routers?
